// @ts-nocheck — generated by `stellar contract bindings typescript`
import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}


export const networks = {
  testnet: {
    networkPassphrase: "Test SDF Network ; September 2015",
    contractId: "CB5ZDO6BPMMWWA3JWOHYEDTMEEY2S37IOEGBXLBS3BJW4MXUODKG4RJ2",
  }
} as const

export const Errors = {
  1: {message:"AlreadyInitialized"},
  2: {message:"NotInitialized"},
  3: {message:"NotListed"},
  4: {message:"AlreadyListed"},
  5: {message:"InvalidPrice"},
  6: {message:"NotSeller"}
}


export interface Listing {
  price: i128;
  seller: string;
}

export interface Client {
  /**
   * Construct and simulate a buy transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Buy a listed `token_id`. Pays the seller and releases the NFT to the buyer.
   */
  buy: ({buyer, token_id}: {buyer: string, token_id: u128}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a init transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Wire the marketplace to the NFT contract and the payment token (a SAC).
   */
  init: ({admin, nft_contract, pay_token}: {admin: string, nft_contract: string, pay_token: string}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a list transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * List `token_id` for `price`. Escrows the NFT into the marketplace.
   */
  list: ({seller, token_id, price}: {seller: string, token_id: u128, price: i128}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a cancel transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Cancel a listing and return the escrowed NFT to the seller.
   */
  cancel: ({token_id}: {token_id: u128}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a pay_token transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * The configured payment token address.
   */
  pay_token: (options?: MethodOptions) => Promise<AssembledTransaction<Result<string>>>

  /**
   * Construct and simulate a get_listing transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Read a listing, if present.
   */
  get_listing: ({token_id}: {token_id: u128}, options?: MethodOptions) => Promise<AssembledTransaction<Option<Listing>>>

  /**
   * Construct and simulate a nft_address transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * The configured NFT contract address.
   */
  nft_address: (options?: MethodOptions) => Promise<AssembledTransaction<Result<string>>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAABAAAAAAAAAAAAAAABUVycm9yAAAAAAAABgAAAAAAAAASQWxyZWFkeUluaXRpYWxpemVkAAAAAAABAAAAAAAAAA5Ob3RJbml0aWFsaXplZAAAAAAAAgAAAAAAAAAJTm90TGlzdGVkAAAAAAAAAwAAAAAAAAANQWxyZWFkeUxpc3RlZAAAAAAAAAQAAAAAAAAADEludmFsaWRQcmljZQAAAAUAAAAAAAAACU5vdFNlbGxlcgAAAAAAAAY=",
        "AAAAAQAAAAAAAAAAAAAAB0xpc3RpbmcAAAAAAgAAAAAAAAAFcHJpY2UAAAAAAAALAAAAAAAAAAZzZWxsZXIAAAAAABM=",
        "AAAAAAAAAEtCdXkgYSBsaXN0ZWQgYHRva2VuX2lkYC4gUGF5cyB0aGUgc2VsbGVyIGFuZCByZWxlYXNlcyB0aGUgTkZUIHRvIHRoZSBidXllci4AAAAAA2J1eQAAAAACAAAAAAAAAAVidXllcgAAAAAAABMAAAAAAAAACHRva2VuX2lkAAAACgAAAAEAAAPpAAAAAgAAAAM=",
        "AAAAAAAAAEdXaXJlIHRoZSBtYXJrZXRwbGFjZSB0byB0aGUgTkZUIGNvbnRyYWN0IGFuZCB0aGUgcGF5bWVudCB0b2tlbiAoYSBTQUMpLgAAAAAEaW5pdAAAAAMAAAAAAAAABWFkbWluAAAAAAAAEwAAAAAAAAAMbmZ0X2NvbnRyYWN0AAAAEwAAAAAAAAAJcGF5X3Rva2VuAAAAAAAAEwAAAAEAAAPpAAAAAgAAAAM=",
        "AAAAAAAAAEJMaXN0IGB0b2tlbl9pZGAgZm9yIGBwcmljZWAuIEVzY3Jvd3MgdGhlIE5GVCBpbnRvIHRoZSBtYXJrZXRwbGFjZS4AAAAAAARsaXN0AAAAAwAAAAAAAAAGc2VsbGVyAAAAAAATAAAAAAAAAAh0b2tlbl9pZAAAAAoAAAAAAAAABXByaWNlAAAAAAAACwAAAAEAAAPpAAAAAgAAAAM=",
        "AAAAAAAAADtDYW5jZWwgYSBsaXN0aW5nIGFuZCByZXR1cm4gdGhlIGVzY3Jvd2VkIE5GVCB0byB0aGUgc2VsbGVyLgAAAAAGY2FuY2VsAAAAAAABAAAAAAAAAAh0b2tlbl9pZAAAAAoAAAABAAAD6QAAAAIAAAAD",
        "AAAAAAAAACVUaGUgY29uZmlndXJlZCBwYXltZW50IHRva2VuIGFkZHJlc3MuAAAAAAAACXBheV90b2tlbgAAAAAAAAAAAAABAAAD6QAAABMAAAAD",
        "AAAAAAAAABtSZWFkIGEgbGlzdGluZywgaWYgcHJlc2VudC4AAAAAC2dldF9saXN0aW5nAAAAAAEAAAAAAAAACHRva2VuX2lkAAAACgAAAAEAAAPoAAAH0AAAAAdMaXN0aW5nAA==",
        "AAAAAAAAACRUaGUgY29uZmlndXJlZCBORlQgY29udHJhY3QgYWRkcmVzcy4AAAALbmZ0X2FkZHJlc3MAAAAAAAAAAAEAAAPpAAAAEwAAAAM=" ]),
      options
    )
  }
  public readonly fromJSON = {
    buy: this.txFromJSON<Result<void>>,
        init: this.txFromJSON<Result<void>>,
        list: this.txFromJSON<Result<void>>,
        cancel: this.txFromJSON<Result<void>>,
        pay_token: this.txFromJSON<Result<string>>,
        get_listing: this.txFromJSON<Option<Listing>>,
        nft_address: this.txFromJSON<Result<string>>
  }
}