// @ts-nocheck — generated by `stellar contract bindings typescript`
import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}


export const networks = {
  testnet: {
    networkPassphrase: "Test SDF Network ; September 2015",
    contractId: "CBRYT3WCYXUINJCW7TV5NRRWROGNFVCG6TA6SMSK4MUDIDJYDLZS7RKF",
  }
} as const

export const Errors = {
  1: {message:"AlreadyInitialized"},
  2: {message:"NotInitialized"},
  3: {message:"TokenNotFound"},
  4: {message:"NotAuthorized"}
}

export interface Client {
  /**
   * Construct and simulate a init transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * One-time initialization. Stores the admin address.
   */
  init: ({admin}: {admin: string}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a mint transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Mint a new token to `to` with metadata `uri`. Anyone may mint (creator economy).
   * Returns the freshly minted token id.
   */
  mint: ({to, uri}: {to: string, uri: string}, options?: MethodOptions) => Promise<AssembledTransaction<Result<u128>>>

  /**
   * Construct and simulate a approve transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Approve `spender` to transfer `token_id`. Caller must be the owner.
   */
  approve: ({owner, spender, token_id}: {owner: string, spender: string, token_id: u128}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a balance transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Number of tokens owned by `owner`.
   */
  balance: ({owner}: {owner: string}, options?: MethodOptions) => Promise<AssembledTransaction<u32>>

  /**
   * Construct and simulate a owner_of transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Current owner of `token_id`.
   */
  owner_of: ({token_id}: {token_id: u128}, options?: MethodOptions) => Promise<AssembledTransaction<Result<string>>>

  /**
   * Construct and simulate a transfer transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Transfer `token_id` from `from` to `to`.
   * 
   * Authorized if `from` is the owner OR an approved spender authorizes the call.
   * When invoked by another contract (e.g. the marketplace escrow holding the
   * token), that contract authorizes its own sub-invocation automatically.
   */
  transfer: ({from, to, token_id}: {from: string, to: string, token_id: u128}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a token_uri transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Metadata URI of `token_id`.
   */
  token_uri: ({token_id}: {token_id: u128}, options?: MethodOptions) => Promise<AssembledTransaction<Result<string>>>

  /**
   * Construct and simulate a get_approved transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * The currently approved spender for `token_id`, if any.
   */
  get_approved: ({token_id}: {token_id: u128}, options?: MethodOptions) => Promise<AssembledTransaction<Option<string>>>

  /**
   * Construct and simulate a total_supply transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Total number of tokens minted so far.
   */
  total_supply: (options?: MethodOptions) => Promise<AssembledTransaction<u128>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAAAAAAADJPbmUtdGltZSBpbml0aWFsaXphdGlvbi4gU3RvcmVzIHRoZSBhZG1pbiBhZGRyZXNzLgAAAAAABGluaXQAAAABAAAAAAAAAAVhZG1pbgAAAAAAABMAAAABAAAD6QAAAAIAAAAD",
        "AAAAAAAAAHVNaW50IGEgbmV3IHRva2VuIHRvIGB0b2Agd2l0aCBtZXRhZGF0YSBgdXJpYC4gQW55b25lIG1heSBtaW50IChjcmVhdG9yIGVjb25vbXkpLgpSZXR1cm5zIHRoZSBmcmVzaGx5IG1pbnRlZCB0b2tlbiBpZC4AAAAAAAAEbWludAAAAAIAAAAAAAAAAnRvAAAAAAATAAAAAAAAAAN1cmkAAAAAEAAAAAEAAAPpAAAACgAAAAM=",
        "AAAAAAAAAENBcHByb3ZlIGBzcGVuZGVyYCB0byB0cmFuc2ZlciBgdG9rZW5faWRgLiBDYWxsZXIgbXVzdCBiZSB0aGUgb3duZXIuAAAAAAdhcHByb3ZlAAAAAAMAAAAAAAAABW93bmVyAAAAAAAAEwAAAAAAAAAHc3BlbmRlcgAAAAATAAAAAAAAAAh0b2tlbl9pZAAAAAoAAAABAAAD6QAAAAIAAAAD",
        "AAAAAAAAACJOdW1iZXIgb2YgdG9rZW5zIG93bmVkIGJ5IGBvd25lcmAuAAAAAAAHYmFsYW5jZQAAAAABAAAAAAAAAAVvd25lcgAAAAAAABMAAAABAAAABA==",
        "AAAAAAAAABxDdXJyZW50IG93bmVyIG9mIGB0b2tlbl9pZGAuAAAACG93bmVyX29mAAAAAQAAAAAAAAAIdG9rZW5faWQAAAAKAAAAAQAAA+kAAAATAAAAAw==",
        "AAAAAAAAAQhUcmFuc2ZlciBgdG9rZW5faWRgIGZyb20gYGZyb21gIHRvIGB0b2AuCgpBdXRob3JpemVkIGlmIGBmcm9tYCBpcyB0aGUgb3duZXIgT1IgYW4gYXBwcm92ZWQgc3BlbmRlciBhdXRob3JpemVzIHRoZSBjYWxsLgpXaGVuIGludm9rZWQgYnkgYW5vdGhlciBjb250cmFjdCAoZS5nLiB0aGUgbWFya2V0cGxhY2UgZXNjcm93IGhvbGRpbmcgdGhlCnRva2VuKSwgdGhhdCBjb250cmFjdCBhdXRob3JpemVzIGl0cyBvd24gc3ViLWludm9jYXRpb24gYXV0b21hdGljYWxseS4AAAAIdHJhbnNmZXIAAAADAAAAAAAAAARmcm9tAAAAEwAAAAAAAAACdG8AAAAAABMAAAAAAAAACHRva2VuX2lkAAAACgAAAAEAAAPpAAAAAgAAAAM=",
        "AAAABAAAAAAAAAAAAAAABUVycm9yAAAAAAAABAAAAAAAAAASQWxyZWFkeUluaXRpYWxpemVkAAAAAAABAAAAAAAAAA5Ob3RJbml0aWFsaXplZAAAAAAAAgAAAAAAAAANVG9rZW5Ob3RGb3VuZAAAAAAAAAMAAAAAAAAADU5vdEF1dGhvcml6ZWQAAAAAAAAE",
        "AAAAAAAAABtNZXRhZGF0YSBVUkkgb2YgYHRva2VuX2lkYC4AAAAACXRva2VuX3VyaQAAAAAAAAEAAAAAAAAACHRva2VuX2lkAAAACgAAAAEAAAPpAAAAEAAAAAM=",
        "AAAAAAAAADZUaGUgY3VycmVudGx5IGFwcHJvdmVkIHNwZW5kZXIgZm9yIGB0b2tlbl9pZGAsIGlmIGFueS4AAAAAAAxnZXRfYXBwcm92ZWQAAAABAAAAAAAAAAh0b2tlbl9pZAAAAAoAAAABAAAD6AAAABM=",
        "AAAAAAAAACVUb3RhbCBudW1iZXIgb2YgdG9rZW5zIG1pbnRlZCBzbyBmYXIuAAAAAAAADHRvdGFsX3N1cHBseQAAAAAAAAABAAAACg==" ]),
      options
    )
  }
  public readonly fromJSON = {
    init: this.txFromJSON<Result<void>>,
        mint: this.txFromJSON<Result<u128>>,
        approve: this.txFromJSON<Result<void>>,
        balance: this.txFromJSON<u32>,
        owner_of: this.txFromJSON<Result<string>>,
        transfer: this.txFromJSON<Result<void>>,
        token_uri: this.txFromJSON<Result<string>>,
        get_approved: this.txFromJSON<Option<string>>,
        total_supply: this.txFromJSON<u128>
  }
}